spring:
  application:
    name: swaggerexam

  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/swagger
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver